---
- hosts: pc-cliente

  tasks:
    - name: Generar clave SSH con valores por defecto y sin passphrase
      community.crypto.openssh_keypair:
        path: /home/user/.ssh/pc-cliente
    
    - name: Conseguir clave SSH creada y pasarla al AMN
      ansible.builtin.fetch:
        src: /home/user/.ssh/pc-cliente.pub
        dest: /home/user/proyecto