---
- hosts: pc-servidor

  tasks:

    # Usuarios
    - name: Copiar clave SSH al servidor
      ansible.builtin.copy:
        src: /home/user/pc-cliente/pc-cliente.pub
        dest: /home/user/.ssh/pc-cliente.pub